[package]
name = "os-walls"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license-file = "../../LICENSE.pending"
publish.workspace = true

[lints]
workspace = true

[dependencies]
os-core.workspace = true
os-model.workspace = true
os-document.workspace = true
os-geometry.workspace = true
os-plugin-api.workspace = true
serde_json.workspace = true
