[package]
name = "os-document"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license-file = "../../LICENSE.pending"
publish.workspace = true

[lints]
workspace = true

[dependencies]
os-core.workspace = true
os-model.workspace = true
os-constraints.workspace = true
serde.workspace = true
